include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml

# services:
#   - quay.io/keycloak/keycloak:latest
#   - minio/minio:latest
#   - plantuml/plantuml-server:jetty
#   - redis:latest
#   - postgres:latest
#   - ghcr.io/solvo-ru/solvo-structurizr:latest
#   - traefik:latest

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

stages:
  - dependency_scanning
  - test


gemnasium-dependency_scanning:
  variables:
    DS_REMEDIATE: "false"
    DS_MAX_DEPTH: -1
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  stage: dependency_scanning