include:
  - template: Jobs/Code-Quality.gitlab-ci.yml

image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: https://docs.gitlab.com/ee/ci/services/index.html
services:
  - quay.io/keycloak/keycloak:latest
  - minio/minio:latest
  - plantuml/plantuml-server:jetty
  - redis:latest
  - postgres:latest
  - ghcr.io/solvo-ru/solvo-structurizr:latest
  - traefik:latest

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

stages:
  - dependency-scanning

dependency-scanning:
  stage: dependency-scanning
  script:
    - npm install
    - npm audit --json
  allow_failure: true
  only:
    - develop
  schedule:
    - cron: "0 0 * * 0" # Weekly schedule, every Sunday at 12:00 AM


