include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml

# services:
#   - quay.io/keycloak/keycloak:latest
#   - minio/minio:latest
#   - plantuml/plantuml-server:jetty
#   - redis:latest
#   - postgres:latest
#   - ghcr.io/solvo-ru/solvo-structurizr:latest
#   - traefik:latest

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache


stages:
  - dependency_scanning
  - code_quality
  - test


gemnasium-dependency_scanning:
  stage: dependency_scanning
  variables:
    DS_REMEDIATE: "false"
    DS_MAX_DEPTH: -1
    DS_ANALYZER_NAME: gemnasium
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  artifacts: 
    paths: [gl-dependency-scanning-report.json]
    reports:
      dependency_scanning: gl-dependency-scanning-report.json

code_quality: 
  variables:
    DOCKER_HOST: kvm-el8-porp.solvo.ru
  stage: code_quality
  artifacts: 
    paths: [gl-code-quality-report.json]
    reports:
      codequality: gl-code-quality-report.json